version: "2"
services:
  kafka:
    image: washpost/kafka:0.11.0.2
    restart: always
    network_mode: host
    volumes:
      - "/data:/data"
    {%- if logging is defined and logging.driver is defined and logging.driver == "awslogs" %}
    logging:
      driver: awslogs
      options:
        awslogs-group: {{ logging.meta.group }}
        awslogs-stream: kafka-${NODE_ID}
    {%- endif %}
    environment:
      INSTANCE_IP: ${INSTANCE_IP}
      BROKER_ID: ${NODE_ID}
      AVAILABILITY_ZONE: ${AVAILABILITY_ZONE}
      ZK_DNS: {{ ZK_DNS }}
    {%- if ZK_PATH is defined %}
      ZK_PATH: "{{ ZK_PATH }}"
    {%- endif %}
    {%- if NUM_PARTITIONS is defined %}
      NUM_PARTITIONS: "{{ NUM_PARTITIONS }}"
    {%- endif %}
    {%- if NUM_IO_THREADS is defined %}
      NUM_IO_THREADS: "{{ NUM_IO_THREADS }}"
    {%- endif %}
    {%- if NUM_REPLICA_FETCHERS is defined %}
      NUM_REPLICA_FETCHERS: "{{ NUM_REPLICA_FETCHERS }}"
    {%- endif %}
    {%- if NUM_NETWORK_THREADS is defined %}
      NUM_NETWORK_THREADS: "{{ NUM_NETWORK_THREADS }}"
    {%- endif %}
    {%- if LOG_DIRS is defined %}
      LOG_DIRS: "{{ LOG_DIRS }}"
    {%- endif %}
    {%- if LOG_MESSAGE_FORMAT_VERSION is defined %}
      LOG_MESSAGE_FORMAT_VERSION: "{{ LOG_MESSAGE_FORMAT_VERSION }}"
    {%- endif %}
    {%- if INTER_BROKER_PROTOCOL_VERSION is defined %}
      INTER_BROKER_PROTOCOL_VERSION: "{{ INTER_BROKER_PROTOCOL_VERSION }}"
    {%- endif %}
    {%- if DEFAULT_REPLICATION_FACTOR is defined %}
      DEFAULT_REPLICATION_FACTOR: "{{ DEFAULT_REPLICATION_FACTOR }}"
    {%- endif %}
    {%- if LOG_RETENTION_HOURS is defined %}
      LOG_RETENTION_HOURS: "{{ LOG_RETENTION_HOURS }}"
    {%- endif %}
    {%- if LOG_RETENTION_BYTES is defined %}
      LOG_RETENTION_BYTES: "{{ LOG_RETENTION_BYTES }}"
    {%- endif %}
    {%- if LOG_SEGMENT_BYTES is defined %}
      LOG_SEGMENT_BYTES: "{{ LOG_SEGMENT_BYTES }}"
    {%- endif %}
